Added UTs for GetAllTribes, GetTotalTribes & GetListedTribes
stakwork/sphinx-tribes pull request #1555
Opened 2024-02-22 22:54 UTC by hkarani

## Describe your changes

## Issue ticket number and link
Issue number 1527
https://github.com/stakwork/sphinx-tribes/issues/1527

## Type of change
Added test to tribes.go for `GetAllTribes`, `GetListedTribes`, `GetTotalTribes`

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## Checklist before requesting a review
- [ ] I have performed a self-review of my code

2024-02-23 12:43 UTC, elraphty requested changes

2024-02-23 12:43 UTC, elraphty commented on handlers/tribes_test.go
> +		rctx.URLParams.Add("tags", tags)
The tags should be in URL query not Params

2024-02-23 12:43 UTC, elraphty commented on handlers/tribes_test.go
> +		rctx.URLParams.Add("tags", tags)
The tags should be in URLQuery, not URLParams

2024-02-23 12:43 UTC, elraphty commented on routes/tribes.go
> +		r.Get("/{tags}", tribeHandlers.GetListedTribes)
Why change the URL and add tags params to it, the tags come come the URL query.

2024-02-24 12:15 UTC, closed without merging

2024-02-24 12:17 UTC, hkarani commented
Created another pull request to fix this.

On Fri, Feb 23, 2024 at 3:43 PM Raphael Osaze Eyerin <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In handlers/tribes_test.go
> <https://github.com/stakwork/sphinx-tribes/pull/1555#discussion_r1500605863>
> :
>
> > +func TestGetListedTribes(t *testing.T) {
> +	mockDb := mocks.NewDatabase(t)
> +	tHandler := NewTribeHandler(mockDb)
> +
> +	t.Run("should only return tribes associated with a passed tag query", func(t *testing.T) {
> +		rr := httptest.NewRecorder()
> +		handler := http.HandlerFunc(tHandler.GetListedTribes)
> +		expectedTribes := []db.Tribe{
> +			{UUID: "1", Name: "Tribe 1", Tags: pq.StringArray{"tag1", "tag2", "tag3"}},
> +			{UUID: "2", Name: "Tribe 2", Tags: pq.StringArray{"tag4", "tag5"}},
> +			{UUID: "3", Name: "Tribe 3", Tags: pq.StringArray{"tag6", "tag7", "tag8"}},
> +		}
> +		rctx := chi.NewRouteContext()
> +		tagVals := pq.StringArray{"tag1", "tag4", "tag7"}
> +		tags := strings.Join(tagVals, ",")
> +		rctx.URLParams.Add("tags", tags)
>
> The tags should be in URL query not Params
> ------------------------------
>
> In handlers/tribes_test.go
> <https://github.com/stakwork/sphinx-tribes/pull/1555#discussion_r1500605895>
> :
>
> > +		assert.EqualValues(t, expectedTribes, returnedTribes)
> +
> +	})
> +
> +	t.Run("should return all tribes when no tag queries are passed", func(t *testing.T) {
> +		rr := httptest.NewRecorder()
> +		handler := http.HandlerFunc(tHandler.GetListedTribes)
> +		expectedTribes := []db.Tribe{
> +			{UUID: "1", Name: "Tribe 1", Tags: pq.StringArray{"tag1", "tag2", "tag3"}},
> +			{UUID: "2", Name: "Tribe 2", Tags: pq.StringArray{"tag4", "tag5"}},
> +			{UUID: "3", Name: "Tribe 3", Tags: pq.StringArray{"tag6", "tag7", "tag8"}},
> +		}
> +		rctx := chi.NewRouteContext()
> +		tagVals := pq.StringArray{}
> +		tags := strings.Join(tagVals, ",")
> +		rctx.URLParams.Add("tags", tags)
>
> The tags should be in URLQuery, not URLParams
> ------------------------------
>
> In routes/tribes.go
> <https://github.com/stakwork/sphinx-tribes/pull/1555#discussion_r1500605948>
> :
>
> > @@ -10,12 +10,13 @@ func TribeRoutes() chi.Router {
>  	r := chi.NewRouter()
>  	tribeHandlers := handlers.NewTribeHandler(db.DB)
>  	r.Group(func(r chi.Router) {
> -		r.Get("/", handlers.GetListedTribes)
> +		r.Get("/{tags}", tribeHandlers.GetListedTribes)
>
> Why change the URL and add tags params to it, the tags come come the URL
> query.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/stakwork/sphinx-tribes/pull/1555#pullrequestreview-1898019687>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AN7TITLIR3CW7KLB6RCCCLDYVCFGRAVCNFSM6AAAAABDVZGHCOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTQOJYGAYTSNRYG4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>