Build endpoint /features/brief and write feature brief to DB
stakwork/sphinx-tribes pull request #1963
Opened 2024-11-18 14:14 UTC by MahtabBukhari

## Describe your changes

## Issue ticket number : #1961
## [Link](https://github.com/stakwork/sphinx-tribes/issues/1961)

## Close: #1961

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have tested on Chrome and Firefox
- [ ] I have tested on a mobile device
- [ ] I have provided a screenshot or recording of changes in my PR if there were updates to the frontend

2024-11-18 15:05 UTC, MahtabBukhari commented
@humansinstitute Could you please review PR as tests are pass?

2024-11-19 00:52 UTC, humansinstitute commented
@MahtabBukhari can you address the failing test? 

```
  Running:  53_workspaceMission.cy.ts                                                     (45 of 59)


  Create Workspace And Update Mission
    1) Creating A Workspace


  0 passing (15s)
  1 failing

  1) Create Workspace And Update Mission
       Creating A Workspace:
     AssertionError: Timed out retrying after 4000ms: Expected to find content: 'carol' but never did.
      at Context.eval (webpack://catcher/./cypress/support/commands.ts:385:0)




  (Results)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Tests:        1                                                                                │
  │ Passing:      0                                                                                │
  │ Failing:      1                                                                                │
  │ Pending:      0                                                                                │
  │ Skipped:      0                                                                                │
  │ Screenshots:  1                                                                                │
  │ Video:        false                                                                            │
  │ Duration:     15 seconds                                                                       │
  │ Spec Ran:     53_workspaceMission.cy.ts                                                        │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


  (Screenshots)

  -  /home/runner/work/sphinx-tribes/sphinx-tribes/tribes-frontend/cypress/screenshot     (1280x720)
     s/53_workspaceMission.cy.ts/Create Workspace And Update Mission -- Creating A Wo               
     rkspace (failed).png           
```

2024-11-19 01:25 UTC, MahtabBukhari commented
@humansinstitute let me check

2024-11-19 03:17 UTC, MahtabBukhari commented
@humansinstitute Could you please review PR now?

2024-11-19 10:03 UTC, tobi-bams requested changes

2024-11-19 10:07 UTC, MahtabBukhari commented on handlers/features.go
> +	ctx := r.Context()
you can review again as checks pass

2024-11-19 10:07 UTC, tobi-bams approved these changes

2024-11-20 10:14 UTC, merged